### ISSUE TITLE
PostgreSQL, MongoDB Backups

### ISSUE THREAD

**Issue by felbinger** [felbinger/GBM#1]
Implement the following features:
* dockerized PostgreSQL backups
* dockerized MongoDB backups

The `config.yaml` could be extended like this:
```
jobs:
...
  postgres:
    - container_name: main_postgres_1
      username: postgres
      password: S3cr3T
      databases:
        - postgres_backup

  mongodb:
    - container_name: main_mongodb_1
      username: backup
      password: S3cr3T
      databases:
        - mongo_backup
```

You can test the new features using the following `docker-compose.yml` in which all required contains are defined:
```yaml
version: '3.9'

services:
  mariadb:
    image: mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=S3cr3T"
      - "MYSQL_USER=backup"
      - "MYSQL_PASSWORD=S3cr3T"
      - "MYSQL_DATABASE=mariadb_backup"

  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=S3cr3T"
      - "POSTGRES_DB=postgres_backup"

  mongodb:
    image: mongo
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=backup"
      - "MONGO_INITDB_ROOT_PASSWORD=S3cr3T"
      - "MONGO_INITDB_DATABASE=mongo_backup"

  ldap:
    image: howardlau1999/openldap-bcrypt
    environment:
      - "LDAP_DOMAIN=domain.com"
      - "LDAP_ADMIN_PASSWORD=S3cr3T"
```
