### ISSUE TITLE
Feature to ignore configured file extensions

### ISSUE THREAD

**Issue by felbinger** [felbinger/GBM#2]
Implement the option to ignore files by there file extension.

The `config.yaml` could be extended like this:
```yaml
jobs:
  files:
    - name: main
      compress: true
      paths:
        - "/srv/main"
      ignore:
        - "/srv/main/ignore_this"
      ignore_extension:
        - "mp4"
```
